spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret-key: softarex
  expire-time: 172800
  refresh-expire-time: 518400
logging:
  level:
    com.nikolai.softarex: debug

cookies:
  domain: localhost

